### ISSUE TITLE
Make build errors

### ISSUE THREAD

**Issue by elfeffe** [segmentio/analytics.js#512]
make build

/media/psf/analytics.js/node_modules/duo/lib/duo.js:1212
    if (e instanceof SyntaxError) throw jsonSyntaxError(e, path);
                                  ^

SyntaxError: Unexpected token } in JSON at position 855
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:558:27)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at readJson (/media/psf/analytics.js/node_modules/duo/lib/duo.js:1210:12)
    at new Duo (/media/psf/analytics.js/node_modules/duo/lib/duo.js:78:15)
    at Function.Duo (/media/psf/analytics.js/node_modules/duo/lib/duo.js:62:38)
    at new Duo (/media/psf/analytics.js/node_modules/duo/bin/_duo:399:14)
    at create (/media/psf/analytics.js/node_modules/duo/bin/_duo:293:13)
    at print (/media/psf/analytics.js/node_modules/duo/bin/_duo:231:13)
    at Object.<anonymous> (/media/psf/analytics.js/node_modules/duo/bin/_duo:194:44)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
make: **\* [analytics.js] Error 1

This is my integrations.js

/\* eslint quote-props: 0 */
'use strict';

module.exports = {
  'adwords': require('analytics.js-integration-adwords'),
  'facebook-conversion-tracking': require('analytics.js-integration-facebook-conversion-tracking'),
  'facebook-custom-audiences': require('analytics.js-integration-facebook-custom-audiences'),
  'google-analytics': require('analytics.js-integration-google-analytics'),
  'google-tag-manager': require('analytics.js-integration-google-tag-manager'),
  'segmentio': require('analytics.js-integration-segmentio'),
  'vero': require('analytics.js-integration-vero'),
};

And this my component.js

{
  "name": "analytics",
  "main": "lib/index.js",
  "repo": "segmentio/analytics.js",
  "description": "The hassle-free way to integrate analytics into any web application.",
  "version": "2.11.0",
  "keywords": [
    "analytics",
    "analytics.js",
    "segment",
    "segment.io"
  ],
  "dependencies": {
    "component/each": "0.0.1",
    "segmentio/analytics.js-core": "^2.10.0",
    "segment-integrations/analytics.js-integration-adwords": "1.0.0",
    "segment-integrations/analytics.js-integration-facebook-conversion-tracking": "1.0.0",
    "segment-integrations/analytics.js-integration-facebook-custom-audiences": "1.0.0",
    "segment-integrations/analytics.js-integration-google-analytics": "1.0.0",
    "segment-integrations/analytics.js-integration-segmentio": "1.0.0",
    "segment-integrations/analytics.js-integration-vero": "1.0.0",
  }
}

npm test says there is no test
I also have some warnings like 
npm WARN eslint-config-segment@1.0.18 requires a peer of eslint-plugin-react@^2.3.0 but none was installed.

How to build it?

**Comment by elfeffe** [comment]
When it says it needs node 0.12, it says it needs node 0.12
It doesn't work with newer versions.

You can install that node version from https://nodejs.org/en/blog/release/v0.12.1/
And then, it works

**Comment by rcline** [comment]
This should be fixed with PR #514

**Comment by lcpriest** [comment]
@elfeffe even when using 0.12.0 I get this same error.
