### ISSUE TITLE
Build fails on missing segmentio-is-email dependency

### ISSUE THREAD

**Issue by nicksloan** [segmentio/analytics.js#559]
I am producing a modified build that only uses Google Analytics and Intercom, and the build fails consistently when Duo is trying to install segmentio-is-email. From the looks of recent commits in core and the integration repositories, Duo support is being dropped.

Can someone offer guidance on what the best approach to a custom build is these days?

**Comment by rae89** [comment]
Any update on this?  I am also receving Duo errors when attempting to build the repo.

**Comment by f2prateek** [comment]
Can you'll share the errors you're seeing? It's hard to say what the issue is without more details.

**Comment by rae89** [comment]
Sure. Here is the build error I get when running `make build` in the analytics.js directory. Afterwards the analytics.js file is empty.

```
$ make build
npm install
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm notice created a lockfile as package-lock.json. You should commit this file.
added 506 packages in 10.215s
touch node_modules
./node_modules/.bin/duo --stdout --standalone analytics lib/index.js > analytics.js

     building : lib/index.js
        using : compatibility
        using : stoj
    installed : component-each@0.0.1
        error : TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at extname (path.js:1471:5)
    at extension (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/duo-main/index.js:135:10)
    at dependency (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/duo-main/index.js:83:16)
    at coerce (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/duo-main/index.js:31:7)
    at Duo.resolve (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/duo/lib/duo.js:798:22)
    at Duo.resolve.next (<anonymous>)
    at next (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/co/index.js:74:21)
    at Duo.<anonymous> (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/co/index.js:45:5)
    at Duo.next (/Users/REspinoza/Projects/segmentio-js/analytics.js/node_modules/co/index.js:90:21)
    installed : segmentio-analytics.js-core@2.12.2


make: *** [analytics.js] Error 1
```

**Comment by omgwtfwow** [comment]
Same error here, did you manage to find a solution @rae89?

**Comment by viperfx** [comment]
@f2prateek @wcauchois 

I am running into the same issue when doing a custom build. 

Any suggestions?

**Comment by wcauchois** [comment]
I ended up using the fork from this PR:
https://github.com/segmentio/analytics.js/pull/514
