### ISSUE TITLE
Cannot build: "path" argument must be of type string

### ISSUE THREAD

**Issue by wcauchois** [segmentio/analytics.js#611]
Hi,

I'm getting an error when building this library from scratch using the `make build` command.

Here is the log:

```
$ make build
npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated classifier@0.1.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@2.3.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 520 packages from 371 contributors and audited 1391 packages in 10.992s
found 45 vulnerabilities (10 low, 17 moderate, 14 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
touch node_modules
./node_modules/.bin/duo --stdout --standalone analytics lib/index.js > analytics.js

     building : lib/index.js
        using : compatibility
        using : stoj
    installed : component-each@0.0.1
        error : TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at extname (path.js:1223:5)
    at extension (/Users/wcauchois/code/analytics.js/node_modules/duo-main/index.js:135:10)
    at dependency (/Users/wcauchois/code/analytics.js/node_modules/duo-main/index.js:83:16)
    at coerce (/Users/wcauchois/code/analytics.js/node_modules/duo-main/index.js:31:7)
    at Duo.resolve (/Users/wcauchois/code/analytics.js/node_modules/duo/lib/duo.js:798:22)
    at Duo.resolve.next (<anonymous>)
    at next (/Users/wcauchois/code/analytics.js/node_modules/co/index.js:74:21)
    at Duo.<anonymous> (/Users/wcauchois/code/analytics.js/node_modules/co/index.js:45:5)
    at Duo.next (/Users/wcauchois/code/analytics.js/node_modules/co/index.js:90:21)
    installed : segmentio-analytics.js-core@2.12.2


make: *** [analytics.js] Error 1
```

Can anyone help me with this issue? Thanks!

**Comment by wcauchois** [comment]
Oops, this appears to be a duplicate of https://github.com/segmentio/analytics.js/issues/559

I'll close this, but a resolution would be appreciated.
