### ISSUE TITLE
Firefox uncaught error: NS_ERROR_FILE_NO_DEVICE_SPACE

### ISSUE THREAD

**Issue by nickpalmer** [segmentio/analytics.js#658]
Our sentry integration just caught the following error from analytics.js:

NS_ERROR_FILE_NO_DEVICE_SPACE: No error message
  at [1195]</o.prototype.remove(/analytics.js/v1/Kxs1uqiSFrakhBTQg8D31RozjRG99m16/analytics.min.js:13:55519)
  at [1193]</i.prototype._reclaim(/analytics.js/v1/Kxs1uqiSFrakhBTQg8D31RozjRG99m16/analytics.min.js:13:53691)
  at e/</<(/analytics.js/v1/Kxs1uqiSFrakhBTQg8D31RozjRG99m16/analytics.min.js:13:52669)
  at [1194]</o.prototype._handle/<(/analytics.js/v1/Kxs1uqiSFrakhBTQg8D31RozjRG99m16/analytics.min.js:13:54585)
  at i(../../../node_modules/@sentry/browser/esm/helpers.js:72:1)

The user is on:

Firefox
Version:87.0

Mac OS X
Version:10.13

I suspect you can trigger this by running Firefox on a machine with no free disk space, but hard to know for sure.

**Comment by sjchmiela** [comment]
FWIW I think I've seen Firefox throw it when trying to access `localStorage` when in private mode
